version: "3"
services:
  redis:
    image: redis
    container_name: redis-broker
    ports:
      - "6379:6379"

  worker1:
    build:
      context: worker/
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  worker2:
    build:
      context: worker/
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
